# Generated by Django 5.2.8 on 2025-11-23 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0003_alter_course_course_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course_image',
            field=models.ImageField(default='course1.png', upload_to='images'),
        ),
        migrations.AlterField(
            model_name='student',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='trainer_photo',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
