# Generated by Django 5.2.8 on 2025-11-23 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0004_alter_course_course_image_alter_student_is_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course_image',
            field=models.ImageField(blank=True, default='course1.png', upload_to='images'),
        ),
    ]
