# Generated by Django 5.2.8 on 2025-11-26 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0006_alter_course_course_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainer',
            name='trainer_photo',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
    ]
