# Generated by Django 5.2.8 on 2025-11-26 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0009_alter_course_course_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainer',
            name='trainer_photo',
            field=models.ImageField(blank=True, default='images/default.jpg', upload_to='images'),
        ),
    ]
